version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=heslo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  me:
    image: mongo-express
    container_name: me
    volumes:
      - ./data-mms:/root/.mms
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=heslo
    depends_on:
      - mongo
  
  mms:
    image: 0dittyspace/lx-mms
    container_name: mms
    volumes:
      - ./data-mms:/root/.mms
    ports:
      - 3333:3333
    environment:
      - PORT=3333
    depends_on:
      - mongo

